<template>
  Switch 的文档
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
  <p>Switch 的文档</p>
</template>

<script>
export default {
  name: "SwitchDemo"
}
</script>

<style scoped>

</style>
